### ISSUE TITLE
IP can easily be spoofed

### ISSUE THREAD

**Issue by krisawzm** [filipac/oc-banip-plugin#1]
IP address can be spoofed by setting either the `X-FORWARDED-FOR` or `CLIENT-IP` header.

Eg.
``` sh
curl -H 'X-FORWARDED-FOR: 127.0.0.1' http://url.tld
```

**Fix proposal:**
Use `\Illuminate\Http\Request\ip()` to fetch the client IP address.

**Comment by filipac** [comment]
thank you :+1:
